language: php

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  - sudo apt-get -qq install graphviz > /dev/null
  ## Composer
  - composer self-update
  - composer install --prefer-source --dev
  - composer require dompdf/dompdf:0.6.*
  ## PHP Copy/Paste Detector
  # - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
  ## PHP Mess Detector
  #- pear config-set preferred_state beta
  #- printf "\n" | pecl install imagick
  #- pear channel-discover pear.phpmd.org
  #- pear channel-discover pear.pdepend.org
  #- pear install --alldeps phpmd/PHP_PMD
  #- phpenv rehash
  ## PHPLOC
  # - curl -o phploc.phar https://phar.phpunit.de/phploc.phar
  ## PHPDocumentor
  - mkdir -p build/docs
  - mkdir -p build/coverage

script:
  ## PHP_CodeSniffer
  - ./vendor/bin/phpcs src/ tests/ --standard=PSR2 -n
  ## PHP Copy/Paste Detector
  # - ./vendor/bin/phpcpd src/
  ## PHP Mess Detector
  - ./vendor/bin/phpmd src/,tests/ text ./phpmd.xml.dist
  ## PHPUnit
  - ./vendor/bin/phpunit -c ./ --coverage-text --coverage-html ./build/coverage
  ## PHPLOC
  - ./vendor/bin/phploc src/
  ## PHPDocumentor
  #- vendor/bin/phpdoc.php -q -d ./src -t ./build/docs --ignore "*/src/PhpWord/Shared/*/*" --template="responsive-twig"

after_script:
  ## PHPDocumentor
  #- bash .travis_shell_after_success.sh
  ## Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
